# ┌──────────────────────────────────────────────────────────────────┐
# │  Application shortcut                                            │
# └──────────────────────────────────────────────────────────────────┘
bindsym Mod4+q       exec sensible-browser
bindsym Mod4+Return  exec i3-sensible-terminal
bindsym Mod4+d       exec rofi -show drun -config ~/.config/i3/rofi/config.rasi
bindsym Mod4+Shift+End exec i3lock-fancy
