# ┌──────────────────────────────────────────────────────────────────┐
# │  Startup application                                             │
# └──────────────────────────────────────────────────────────────────┘
exec setxkbmap -layout fr,fr
exec xinput --map-to-output 11 eDP-1
exec dex -ae i3
exec --no-startup-id nm-applet
exec --no-startup-id xfce4-power-manager
exec --no-startup-id redshift
exec --no-startup-id "killall -q compton; compton --config ~/.config/i3/conf/compton.conf"
exec --no-startup-id "copyq"
