# ┌──────────────────────────────────────────────────────────────────┐
# │  Startup application                                             │
# └──────────────────────────────────────────────────────────────────┘
exec_always --no-startup-id ~/.config/i3/scripts/map_touchscreen.sh
exec --no-startup-id dex -ae i3
exec --no-startup-id nm-applet
exec --no-startup-id xfce4-power-manager
exec --no-startup-id redshift
exec --no-startup-id "killall -q picom compton; picom --config ~/.config/i3/conf/picom.conf"
exec --no-startup-id "killall -q dunst; dunst -config ~/.config/i3/dunst/dunstrc"
exec_always --no-startup-id ~/.config/i3/scripts/launch_polybar.sh
exec --no-startup-id "diodon"
